### ISSUE TITLE
Can you help?

### ISSUE THREAD

**Issue by ValdemarLarsen** [danielyc/csb#10]
So when i try to type "Run start" as you says i need to do here "or on Mac run start." so i hope you can help me 

//Valdemar

**Comment by danielyc** [comment]
Please don’t make an issue asking for help using CSB. Contact us via email or twitter.

**Comment by ValdemarLarsen** [comment]
What is the mail when i try to send a mail to the one on you site then i says it dosent work

**Comment by danielyc** [comment]
Contact us via twitter while I fix the website/email

**Comment by ValdemarLarsen** [comment]
where do i find you're twitter

**Comment by ValdemarLarsen** [comment]
i found it
