### ISSUE TITLE
Add the possibility to choose minute and seconds of the drop

### ISSUE THREAD

**Issue by Ludoboii** [danielyc/csb#5]
**Is your feature request related to a problem? Please describe.**
Not really, but it would make it easier to choose a drop time closer to the actual drop.

**Describe the solution you'd like**
Make it possible to set hour, minute and seconds of the drop before adding an item.

**Describe alternatives you've considered**
Make it possible to set how many seconds before the selected time of the drop the bot should start looking for the item.

**Comment by danielyc** [comment]
Good suggestion, we will work on it.

**Comment by danielyc** [comment]
Next update will have this feature.
