### ISSUE TITLE
Can not connect to the Service. /chromedriver

### ISSUE THREAD

**Issue by Kevinkylel** [danielyc/csb#7]
Traceback (most recent call last):
  
File "main.py", line 127, in go
  
File "bot.py", line 252, in openChrome
  
File "site-packages/selenium/webdriver/common/service.py", line 104, in start
  
selenium.common.exceptions.WebDriverException: Message: Can not connect to the Service ./chromedriver
  
Traceback (most recent call last):
  
File "main.py", line 127, in go
  
File "bot.py", line 252, in openChrome
  
File "site-packages/selenium/webdriver/common/service.py", line 98, in start
  
File "site-packages/selenium/webdriver/common/service.py", line 111, in assert_process_still_running
  
selenium.common.exceptions.WebDriverException: Message: Service ./chromedriver unexpectedly exited. Status code was: 1

**Comment by danielyc** [comment]
Please follow the issue template. We can't help you if you only supply the python error.

**Comment by Kevinkylel** [comment]
On macOs 10.12.4
chromedriver in the same folder as CSB
Have the CSB-Mac version.

Ran start
-able to make new config 
-setup task then pressed go.
-there is a slight pause then the python error emerges.

**Comment by danielyc** [comment]
do you have chrome installed in the default path?

**Comment by Kevinkylel** [comment]
By default path do you mean in the same folder?  Upon downloading and installing chrome, its placed in the applications folder.  I did take note on the instruction regarding chromepath.txt, but I'm not sure how to correctly write the path if that is the issue.

**Comment by danielyc** [comment]
Then it's in the correct location. i've never had this issue so i think it has something to do with your configuration. can you run "./chromedriver --version"?

**Comment by Kevinkylel** [comment]
Binary

**Comment by danielyc** [comment]
try out this fix,
http://www.mediafire.com/file/r3zfbiwb8870pcn/CSB-MAC.zip

**Comment by Kevinkylel** [comment]
Did a screen recording to have a better visual.
https://youtu.be/aeD8VZXw9QU

**Comment by danielyc** [comment]
That’s a different error than the one before.

**Comment by Kevinkylel** [comment]
Was doing some research: https://stackoverflow.com/questions/25080500/when-running-webdriver-with-chrome-browser-getting-message-only-local-connect

"I was getting the exact same errors. I battled this issue for a few hours today. It seemed to be caused by a mismatch between the versions of chromedriver and selenium-server-standalone. The config.js file was referencing a directory that had chromedriver 2.9 and selenium-server-standalone 2.35.0. Once I made sure we were referencing 2.10 and 2.42.2, it worked."

Please explain what could be the possible issue?

**Comment by Kevinkylel** [comment]
https://stackoverflow.com/questions/50727595/selenium-common-exceptions-webdriverexception-message-can-not-connect-to-the-s

**Comment by Kevinkylel** [comment]
There was no output from the command "cat /etc/hosts" when inputted into the terminal

**Comment by danielyc** [comment]
then make that file with the following content:
##
##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting. Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1 localhost
fe80::1%lo0	localhost

**Comment by Kevinkylel** [comment]
Replaced my hosts file with a new one (took some time given some permission issues) but I'm glad to say that the program works now! Question: When will you roll out the updated version of CSB with the option to edit minutes and seconds?

**Comment by danielyc** [comment]
i'm glad to hear that.
