### ISSUE TITLE
Size adjustments (dealing with a sold out size) & Early drop times or delays

### ISSUE THREAD

**Issue by Kevinkylel** [danielyc/csb#8]
**Is your feature request related to a problem? Please describe.**
Today (9/20/18) I was prepping my computer by syncing the times as close as possible to the current time so when the drop counter was initiated that it would run smoothly as possible.  However, Supreme may, or may not, drop exactly at 11 EST and either it drops to early or there is a delay so I set the bot to run a few seconds before the drop (10:59:55)

-Signed in to gmail
-unable to do 4chan captchas

Come drop time (10:59:55), the bot worked initially, bc by 11AM, the bot started by adding the first two pieces, then it got hung up. Next I knew, the two pieces added to cart were sold out.  Happened within a 10 sec window.
Mind you, that I inputted 4 hype pieces into the bot so maybe that was also an issue.

Edit* ended up going manual, W on the initial drop and more W on the restocks.

**Describe the solution you'd like**
-If the item in a certain size is sold out can it just skip to the next few items on the list without delay
-If the item in a certain size is sold out, can the bot quickly adjust to what is available
-In addition to having a timer setup, can the bot have a page monitor setup to assist in the issues on Supreme drop times (early or delayed)

**Describe alternatives you've considered**
Combined in the suggestions above /\

**Comment by danielyc** [comment]
First two options will be added but the last option is not gonna work sometimes because supreme will kick you out if you request the same page to much
