### ISSUE TITLE
Add Checkout and cart delay

### ISSUE THREAD

**Issue by MLWALK3R** [danielyc/csb#9]
Add a checkout & cart delay. I'm wondering if instantly adding items and checking out straight after is triggering recaptcha; I've never had it with other bots and the times I've used CSB its been triggered every time, and they're never ending.

**Comment by danielyc** [comment]
did those bots use selenium in combination with chromedriver?

**Comment by MLWALK3R** [comment]
I doubt it.

This is the bot I used https://chrome.google.com/webstore/detail/supreme-auto-checkout-bot/lokkgfofiabinmcohpdalkcmfjpepkjb

**Comment by danielyc** [comment]
that works from within chrome, CSB works with an other system. You can not verify that that plugin doesn't send your payment credentials to some remote server btw. I'm gonna close the issue because this is basically part of the recapcha bypass.

**Comment by MLWALK3R** [comment]
Pretty sure you can just audit the code and run your own version since its open-source on Github (convenience over security comes to mind)
